### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by pokemon81** [forelleblau/ioBroker.smappee#5]
hello,
i become the following error message:  

MAIN: JSON-parse-Fehler Message: Unexpected end of JSON input
--

i have reinstall adapter. Ich see mqtt messages in my object they actual.
What can i test btw. send to you that you can help me.

my json input from smappee in mqtt is the following:

{"totalPower":195,"totalReactivePower":147,"totalExportEnergy":0,"totalImportEnergy":82659,"monitorStatus":0,"utcTimeStamp":1552680604151,"channelPowers":[{"ctInput":0,"power":39,"exportEnergy":0,"importEnergy":2004,"phaseId":0,"current":5},{"ctInput":1,"power":7,"exportEnergy":0,"importEnergy":7599,"phaseId":1,"current":1},{"ctInput":2,"power":149,"exportEnergy":0,"importEnergy":73057,"phaseId":2,"current":12}],"voltages":[{"voltage":235,"phaseId":0}]}

**Comment by pokemon81** [comment]
roblem was tha in the Adapter was configured "localhost" i must set the ip adress then it works.

**Comment by forelleblau** [comment]
Thanks for the feedback...and for using smappee - adapter.

**Comment by pokemon81** [comment]
Hi,

i had the next Problem. My Obects not acutual. i become the message:

"Unexpected end of JSON Input"

but the First power is shown only one time then it come nothing and no error. 

Sorry

**Comment by forelleblau** [comment]
Hallo pokemon81. 
Soll ich auf Deutsch antworten?

**Comment by pokemon81** [comment]
Ja gerne, das macht es einfacher für mich. ;)

**Comment by forelleblau** [comment]
Also. Wenn ich dich richtig verstehe
- werden die Smappee-Objekte in der mqtt-Instanz aktualisiert (das realtime-Objekt 'blinkt' grün).
- in der Smappee - Instanz wird das Objekt aber nur beim Neustart des Adapters aktualisiert.
- Taucht die Fehlermeldung ...JSON-Input... nur einmal beim Neustart auf.

Wenn das so ist
- kannst du die Fehlermeldung ignorieren, die taucht bei mir beim Neustart auch auf, weil die erste Nachricht von mqtt eintrifft, bevor der Adapter sie verarbeiten kann. 

 - Für die generelle Situation kannst du prüfen, ob dein mqtt-Adapter auf Port 1883 läuft (ist Standard für mqtt). Das ist auch der, den du beim Smappee im Admin eingetragen hast. Wenn das nicht Port 1883 ist, müsstest du das in der smappee-Instanz-Config eintragen. 

- du hast weiter oben gesagt, dass du in der smappee-Instanz-config eine IP eingetragen hast. Versuch einmal neben der IP auch den Port einzutragen (1883 oder den, den du in der mqtt-Instanz definiert hast).

- Wenn das nicht hilft
a) nach dem Adapter Neustart einmal in der Objekt-Ansicht die Ansicht aktualisieren (mit dem Rundpfeil oben), alle smappee-Objekte aufklappen und mir einen Screenshot schicken.
b) das LOG für die smappee-Instanz auf debug stellen und mir ein LOG eines Adapter-Neustarts schicken.

Danke u Gruss
forelleblau

**Comment by pokemon81** [comment]
Also folgendes. du hast es genau richtig verstanden. Die Werte kommen und blinken Grün. Hier passt meiner Meinung nach alles MQTT Instanz läuft bei mir ja auch für andere Geräte. Ich sehe auch das in MQTT die Datenpunkte erstellt werden Wenn ich diese Lösche  werden Sie neu angelegt.

Wenn ich im Smappee absichtlich einen falschen Port oder ip angebe werde keine Werte mehr in MQTT geschrieben. Also gehe ich hier nicht von einem Problem zwischen Smappee und MQTT aus. 

Die Fehler Meldung des Adapters kommt immer beim starten. Dann schriebt er auch 1x einen Wert rein aber danach passiert nichts mehr. ich teste gerade noch die
![19-03-_2019_11-25-17](https://user-images.githubusercontent.com/8666185/54599156-55d39900-4a3a-11e9-992b-60e7323fb5c4.jpg)
[smappee.log.txt](https://github.com/forelleblau/ioBroker.smappee/files/2982815/smappee.log.txt)

 IP fest zu hinterlegen und gebe den Port mal an. Ich sende dir hier schonmal die Logfiles und den Screenshot.

LG und vielen Dank schonmal

**Comment by forelleblau** [comment]
Hallo Pokemon81
- Also an den Adapter-Einstellungen wird's nicht liegen, die Verbindung wird einwandfrei aufgebaut. Ebenso werden die reinkommenden Messages verarbeiten, die nötigen Objekte angelegt und die Daten gelesen und gesetzt. Letzteres aber nur genau 1 mal pro Message. Dann steht das Ganze - wieso kann ich mir im Moment nicht erklären. Eigentliche sieht es so aus, als kämen keine Messages mehr rein.
Kannst du mir bitte einmal ein Log zur Verfügung stellen, das neben den smappe-debug-Ereignissen auch die mqtt-debug-Ereignisse umfasst?

Was deine software-Umgebung anbelangt (ioBroker admin/js-controller, node.js) gehe ich davon aus, dass sie up to date ist. Mehr kann ich ev. heute abend sagen, wenn ich wieder Zugriff auf meine Umgebung habe.

Gruss
forelleblau.

**Comment by pokemon81** [comment]
Ja der Adapter an sich wirft auch keinen Fehler. Die Meesages an MQTT kommen rein. 
Ich bin auf den empfohlenen versionen von NPM und Node (extra nicht die neueeste bzgl. Support aus dem Forum hier) 

Ich habe dir mal einen Auschnitt gemacht von meinem MQTT log dort sieht man auch das der Smappee immer sendet. Nur scheinbar aktualisiert sich der Smappee adapter nicht wenn sich etwas im mqtt ändert. 

die frage wäre wie dein Adapter die aktualisierung mitbekommt ? Alle 5 minuten (würde mir sogar reichen) oder in echtzeit per sek. ?

![19-03-_2019_14-14-30](https://user-images.githubusercontent.com/8666185/54608895-11ec8e00-4a52-11e9-92bb-8019bf798f93.jpg)
[mqtt.log](https://github.com/forelleblau/ioBroker.smappee/files/2983488/mqtt.log)

**Comment by pokemon81** [comment]
also ich denke ich habe den Fehler gefunden !

Ich habe den Smappee komplett zurückgesetzt. Leider sind dabei meine gespeicherten Daten von 4 Jahren weg geflogen - aber egal. Nachdem ich dann einen neuen MQTT Broker eingebunden hab konnte ich den Fehler nachstellen. 

Der Punkt MQTT -> "publish nur bei änderung" muss aktiviert werden. dann wird der Smappee adapter auch korrekt aktualisiert. Ich hatte diesen Punk nicht angehakt daher kam der Fehler. 

Danke für deine Hilfe - toller Adapter, mach weiter so.
![error-found](https://user-images.githubusercontent.com/8666185/54619848-8da40600-4a65-11e9-9b7d-0e4f8b6089c1.jpg)

**Comment by forelleblau** [comment]
Hallo pokemon81
Das mit deinen Daten tut mir leid. Aber danke für die intensive und erfolgreiche Fehlersuche. Bei mir ist "Publish nur bei Änderung" auf jeden Fall aktiviert. Ich werde diesen Hinweis ins README aufnehmen.
Es freut mich, dass es jetzt funktioniert.
